### ISSUE TITLE
How to access the refresh token?

### ISSUE THREAD

**Issue by sagepawan** [Azure-Samples/active-directory-b2c-android-native-msal#6]
The `AuthenticationResult` at `AuthenticationCallback` success only gives the access token. How do we get the refresh token using this implementation?

**Comment by danieldobalian** [comment]
MSAL doesn't expose the refresh token today. Can you speak to why your apps need it? The calling pattern assumes you can ask for a fresh access token anytime your app needs to call an API. Does this not cover a scenario for you?
