### ISSUE TITLE
Problem with subsequent Google Logins after Logout

### ISSUE THREAD

**Issue by mahesh87ta** [Azure-Samples/active-directory-b2c-android-native-msal#7]
For the very first time, when attempting to login using Google, user is prompted for selecting the google accounts.. After logout from the application, subsequent logins doesn't prompt for selecting the google accounts, and directly logins with the previous google account.. 
Kindly help me out in resolving this issue.

**Comment by parakhj** [comment]
When you sign out of Azure AD B2C, you do not sign out of Google. So you will not need to enter the google credentials again.

You should still however see the identity provider selection screen after logging out. If not, then you may not be logging out correctly.

**Comment by mahesh87ta** [comment]
I am always seeing identity provider selection screen after logging out, my concern is 
If I logged in using abc@gmail.com and logged my my app as Google, next time I want to logged in with different account as xyz@gmail.com, but it is not allowing to login with different account, it is always try to login with abc@gmail.com as silently when I clink login in with Google button. Kindly let me know your reply.

**Comment by parakhj** [comment]
You will need to first go to a Google site and log out from there

**Comment by PraveenVerma17** [comment]
MSFT should logout gmail users also or remove these features....if you are not able to support.
